tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'

brew 'ack'
brew 'bat'
brew 'git'
brew 'hub'
brew 'heroku/brew/heroku'
brew 'nvm'
brew 'openssl'
brew 'thefuck'
brew 'tldr'
brew 'trash'
brew 'watchman'
brew 'youtube-dl'
brew 'zsh-syntax-highlighting'
brew 'zsh-autosuggestions'

cask 'android-file-transfer'
cask 'caffeine'
cask 'dropbox'
cask 'filezilla'
cask 'firefox'
cask 'franz'
cask 'flux'
cask 'google-chrome'
cask 'imageoptim'
cask 'iterm2'
cask 'jumpcut'
cask 'macdown'
cask 'spectacle'
cask 'sourcetree'
cask 'the-unarchiver'
cask 'transmission'
cask 'visual-studio-code'
cask 'vlc'

# QuickLook plugins
cask 'betterzip'
cask 'qlcolorcode'
cask 'qlmarkdown'
cask 'qlprettypatch'
cask 'qlstephen'
cask 'quicklook-csv'
cask 'quicklook-json'
cask 'webpquicklook'

# Custome font
cask 'font-fira-code'
