cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'git'
brew 'n'
brew 'openssl'
brew 'thefuck'
brew 'trash'
brew 'youtube-dl'

tap 'caskroom/cask'

cask 'android-file-transfer'
cask 'atom'
cask 'caffeine'
cask 'dash'
cask 'dropbox'
cask 'filezilla'
cask 'firefox'
cask 'franz'
cask 'google-chrome'
cask 'imageoptim'
cask 'iterm2'
cask 'macdown'
cask 'megasync'
cask 'spectacle'
cask 'sourcetree'
cask 'the-unarchiver'
cask 'transmission'
cask 'vlc'

cask 'qlcolorcode'
cask 'qlstephen'
cask 'qlmarkdown'
cask 'quicklook-json'
