export ZSH=/Users/luca/.oh-my-zsh
ZSH_THEME="robbyrussell"

plugins=(git git-extras git-flow git-prune github npm terminalapp)

source $ZSH/oh-my-zsh.sh

# install pure prompt installed via npm
autoload -U promptinit; promptinit
prompt pure

# zsh-plugins installed via brew
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

export PATH="$PATH:./node_modules/.bin"

export HISTSIZE=10000
export SAVEHIST=$HISTSIZE
setopt hist_ignore_all_dups
setopt hist_ignore_space

eval "$(thefuck --alias)"

for file in $HOME/dotfiles/zsh/{aliases,apikeys,functions}; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;
