export ZSH=/Users/luca/.oh-my-zsh
ZSH_THEME=""
DISABLE_MAGIC_FUNCTIONS=true

plugins=(copyfile git git-extras git-flow github history macos zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

eval "$(starship init zsh)"

export PATH="$PATH:./node_modules/.bin"

export HISTSIZE=10000
export SAVEHIST=$HISTSIZE
setopt hist_ignore_all_dups
setopt hist_ignore_space

eval "$(thefuck --alias)"

eval "$(mcfly init zsh)"

for file in $HOME/dotfiles/zsh/{aliases,apikeys,functions}; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

export NVM_DIR="$HOME/.nvm"
  [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && . "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && . "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion